// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAymmYwmJgHoVeQmVIzBFSG4eRJYk0CFw8',
    appId: '1:614955579913:web:3da886532c756d961f16d8',
    messagingSenderId: '614955579913',
    projectId: 'saude-digital-14b47',
    authDomain: 'saude-digital-14b47.firebaseapp.com',
    databaseURL: 'https://saude-digital-14b47-default-rtdb.firebaseio.com',
    storageBucket: 'saude-digital-14b47.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCezdLKWIOs9feVwQ8A5oFmRiUlhrXRH14',
    appId: '1:614955579913:android:f5e729225e9bb4511f16d8',
    messagingSenderId: '614955579913',
    projectId: 'saude-digital-14b47',
    databaseURL: 'https://saude-digital-14b47-default-rtdb.firebaseio.com',
    storageBucket: 'saude-digital-14b47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsuS138j22rQDWT645YQrgTzGnboDyJY4',
    appId: '1:614955579913:ios:9148862121d9bcc61f16d8',
    messagingSenderId: '614955579913',
    projectId: 'saude-digital-14b47',
    databaseURL: 'https://saude-digital-14b47-default-rtdb.firebaseio.com',
    storageBucket: 'saude-digital-14b47.appspot.com',
    iosClientId: '614955579913-ut3q0o93gp4atua3jenre6ug2gk2olrh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
